### ISSUE TITLE
Erorr when installing locally

### ISSUE THREAD

**Issue by Pavel-Durov** [soldair/node-s3-npm#7]
Hi, I've encountered this issue when I've tried to install it locally. 
Don't know if it is intentional or not :)

Reproduction steps:

1. `npm install s3npm -D`
2.  `./node_modules/.bin/s3npm configure`
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at evalmachine.<anonymous>:44:31
    at Object.<anonymous> (/home/pavel/git-repos/nate/nate.chromeextension/node_modules/npm/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by soldair** [comment]
this is a super old project so if you figure it out feel free to make a pull request. otherwise i'm unlikely to work on it.
